### ISSUE TITLE
Updater

### ISSUE THREAD

**Issue by root1599** [MylesIsCool/ViaVersion#1096]
**Is your feature request related to a problem? Please describe.**
My server network never had the latest build and i always have to hassle over to the website and remote desktop on all my servers and download the plugin

**Describe the solution you'd like**
A command to update the plugin, not an autoupdate, just a command i could use to update it

**Describe alternatives you've considered**
I have searched for autoupdate plugins and found none

**Which versions is this for?**
all

**Comment by MylesIsCool** [comment]
There are a few issues on our GitHub which explain why we don't have this, I'll leave you to read these if you want to know.

Otherwise, you can use a script to download the latest version from ci.viaversion.com (There are notes on https://docs.viaversion.com/display/VIAVERSION/Installation)

There will never be an auto-updater, mainly because you become out of the loop with known issues etc.
