### ISSUE TITLE
Villager

### ISSUE THREAD

**Issue by Misio12320** [MylesIsCool/ViaVersion#1153]
Hello. ViaVersion-DEV bug report - every join server the chunks are clear,right click on green villager it crash 19w02a everyone villager is the same, campfire is getting to stone change everytime i take it from inventory game-mode creative every new block are going to stone.. Will on the wednesday release a bigger bug-fix ?

**Comment by Gerrygames** [comment]
Villagers metdata and the client crash related to it has been fixed in the latest PR from creeper #1154. 
That chunks are sometimes not loading correctly is known, but unfortunately we haven’t figured out what exactly is causing it.
What are you expecting when taking new items from the creative inventory. Should they just magically work? ViaVersion only provides client support on a protocol level and does not add any features of newer versions to the server. New items are mapped to stone on every version that’s supported by ViaVersion.
We (myles and all contributors) are of course working on fixing all the issues before releasing a new version. But issues in our development builds do not have a high priority, because they are not meant for production usage and sometimes we do wait for the next snapshot, which could change something or fix some issue.

**Comment by MylesIsCool** [comment]
See above :) Gerry said it very well.
