### ISSUE TITLE
ProtocolLib unable to send packet: nmsPlayer cannot be null!

### ISSUE THREAD

**Issue by MClausz** [MylesIsCool/ViaVersion#197]
### What version of ViaVersion are you using? Type /ver viaversion
0.6.3
### What version of Spigot are you using? Type /ver
paperspigot and spigot 1.8.8
### What plugins are you using? Type /plugins
Plugins (48): PlugMan, EnchantmentAPI, DeathDropsAPI, ItemCasesFix, ViaVersion, ChestShopCreate, AsyncWorldEditInjector, EnchantManager, WorldEdit, EmptyWorldGenerator, SkinsModule, DefaultSkinsBungeeCordSub, NBTEditor, ClearLag, TimedItems, EnchantPotionPack, ProtocolLib, NoCheatPlus, AsyncWorldEdit, PermissionsEx, EnchantActivePack, EffectLib, Vault, EnchantPassivePack, ItemHolo, PlayerPoints, WorldGuard, BungeePortals, ASkyBlock, ChestCommands, LockedItems, CheckMyInventory, EnchantIntensePack, Essentials, MCTopup, Multiverse-Core, Citizens, Shopkeepers, EssentialsChat, Multiverse-Portals, HolographicDisplays, EssentialsSpawn, MyPet, ItemCases, PlaceholderAPI, BetterShops, BungeeTabListPlus, TitleManager
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Lasted build, plugins: JustOneMore, BungeeTabListPlus, ServerListPlus, SkinsRestorer.
Players can connect to lobby but can't connect to SkyBlock server
### How does this error happen? login? Using an item? 
login
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/tchJSTSW

**Comment by HugoDaBosss** [comment]
So does the same error occur on paperspigot and spigot?
Also it's really strange because these two lines are contradictory: 
`[06:26:16] [Server thread/WARN]: [ProtocolLib] Error filtering reports: java.lang.IllegalArgumentException: Cannot find report name for Unable to send packet %s to %s
[06:26:16] [Server thread/WARN]: [ProtocolLib] [ProtocolLibrary] Unable to send packet net.minecraft.server.v1_8_R3.PacketPlayOutMapChunk@b9ee16e to EarthBound_Ness`
Somehow the nms player got invalidated, are you sure you are using ProtocolLib for 1.8?
I assume this error doesn't happen without ViaVersion?
Does this happen for just 1.9 players? And does it happen from server startup, or is it sometimes randomly that this happens?

**Comment by MClausz** [comment]
I'm using recomended ProtocolLib build for spigot 1.8, happen for just 1.9 players when they join.
Also tried paperspigot.
It works fine on Lobby, but when a player tries to connect to skyblock, bungeecord sends player back to lobby.

**Comment by MClausz** [comment]
I will remove one by one plugin to see what plugin causes the issue when I have time.

**Comment by HugoDaBosss** [comment]
Does this error only apply to the MapChunkBulk packet or does it also list other packets in the error?

**Comment by MClausz** [comment]
The problem was CheckMyInventory, reported to the developer.
https://www.spigotmc.org/threads/check-my-inventory-offline-player-support-paid.48111/

**Comment by MylesIsCool** [comment]
Closed, CheckMyInventory has fixed their code.

**Comment by MedicOP** [comment]
What caused the issue? I'm having the same issue right now with my own plugin
