### ISSUE TITLE
Splash Water Bottle in place of water breathing potion

### ISSUE THREAD

**Issue by DataPools** [MylesIsCool/ViaVersion#385]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.9
### What version of Spigot are you using? Type /ver
PaperSpigot 1.8.4
### What plugins are you using? Type /plugins
EssentialsX, ViaVersion
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
N/A
### How does this error happen? login? Using an item? 
When buying a splash potion of water breathing (ID: 373:16429 for 1.8) using EssentialsEco signs, a splash water bottle is given. However, when the user uses the splash water bottle it gives them water breathing. This does not happen with any other potion. If I were to join on 1.8, the signs & potions work perfectly.
On 1.9, all previous water breathing potions in my inventory are turned into splash water bottles.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
None

**Comment by MylesIsCool** [comment]
This potion doesn't technically exist in 1.9, you're using the wrong ID. You're making a potion with Tier II breathing, which is not possible in vanilla and does not exist in 1.9.

See http://minecraft-ids.grahamedgecombe.com/potion-calculator, I'd suggest changing the IDs on your signs to 16397.

I'm unsure if we'll fix this because even if we did, the potion would still have incorrect data when hovered over.

**Comment by DataPools** [comment]
Couldn't ViaVersion have items with that specific ID for 1.9 clients changed to the correct ID for 1.9?

I'm not sure if that ID works for 1.8

**Comment by MylesIsCool** [comment]
Going to close this as you shouldn't ever have this potion in Minecraft, the change as suggested in my post above does work fine.
