### ISSUE TITLE
1.10.1 crash (wall sign?)

### ISSUE THREAD

**Issue by PhanaticD** [MylesIsCool/ViaVersion#446]
### What version of ViaVersion are you using? Type /ver viaversion
0.9.5-SNAPSHOT build 37

### What version of Spigot are you using? Type /ver
This server is running Paper version git-Paper-772 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)

### How does this error happen? login? Using an item? 
on login

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/2MCaFgPX

**Comment by Matsv** [comment]
Hi, could you try normal Spigot 1.9.4, and see if it happens there?

**Comment by PhanaticD** [comment]
considering mojang has said they are going to be "fixing the issues with 1.10.1" its probably their fault :P

**Comment by MrPowerGamerBR** [comment]
This same crash also happened to me, but instead of a sign, it was a enderchest: https://gist.github.com/MrPowerGamerBR/c2cc7cecede5943aec92219856fa6fe1

I didn't post a separate issue because I don't run the latest & official ViaVersion, I'm running a "not-so-official" ViaVersion for 1.7.10, but I decided to share the crash report... maybe it will help with something...

I hope Mojang fixes the issue in 1.10.2.

**Comment by Matsv** [comment]
@MrPowerGamerBR Pull the changes in your non-official ViaVersion, that should fix it.

**Comment by Matsv** [comment]
I doubt it that Mojang will remove this check completely.

**Comment by Matsv** [comment]
Well, turns out they removed the exception completely on 1.10.2.
