### ISSUE TITLE
Sponge Port

### ISSUE THREAD

**Issue by Maxqia** [MylesIsCool/ViaVersion#458]
Do you have any plans for porting ViaVersion to the Sponge API? I'd really like to use this plugin on my Sponge Servers.

**Comment by MylesIsCool** [comment]
See

https://forums.spongepowered.org/t/1-9-clients-connecting-to-1-8/12210/7?u=myles

It's a lot of work to do unfortunately, hence we'd only do it if there was sufficient want to make it worthwhile.

**Comment by sgdc3** [comment]
Fu** sponge! xD

**Comment by Cecer** [comment]
Just throwing in that this is something that would've potentially helped out a few things in the past where Spigot/Bukkit were not a reasonable option but Sponge was.

**Comment by MylesIsCool** [comment]
@Cecer for example?

**Comment by Cecer** [comment]
It's not something I am at liberty to disclose, sorry. By no means would my needs alone warrant the effort for a sponge port but consider me interested in seeing it happen if enough other people are too.

**Comment by Maxqia** [comment]
:/ I see you're started working on sponge support ... , I had it working for months in a dev environment with Pore but haven't released it yet (Time to do that I guess), Anyways +1 for modularity

**Comment by MylesIsCool** [comment]
@Maxqia Yeah we're working towards being more multiplatform, which I wasn't expecting to be able to add sponge compatibility so early on but it seems just like an obfuscation mapping thing. Sadly pore is discontinued which is one of the reasons we wanted "native" ish support. 

Otherwise this is my first ever Sponge plugin, if there's any mistakes or things that could work better on the Sponge environment i'd love your input / contribution. (Some things are obviously WIP at this point in time)
Or simply if you want to test and find bugs, there will be one of two... because they slip in but hey,

**Comment by Matsv** [comment]
We created basic support for Sponge now, we still have to implemented some minor functionality. 
If anyone of you owns/runs a Sponge server, please help us improve the Sponge support by testing and reporting bugs at #505.

please follow #505 for further updates about this topic.
