### ISSUE TITLE
1.9 to 1.8 packet entity witch metadata error

### ISSUE THREAD

**Issue by mastercake10** [MylesIsCool/ViaVersion#511]
### What is the output link of /viaversion dump?

using ViaVersion 0.9.4

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

using DisguiseCraft-API for disguising player in a witch

### How does this error happen? login? Using an item? 

on api call from DisguiseCraft-API. Other disguises/entities are working.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

Yes, here is the error: http://pastebin.com/94DLwR1e

**Comment by Matsv** [comment]
Looks like one of your plugins is sending wrong metadata.

Make sure that your plugin (Disguisecraft-API) is compatible with Spigot 1.8.8
1.8 metadata: http://wiki.vg/index.php?title=Entities&oldid=7375#Human

Otherwise you can change the config option 'suppress-metadata-errors' to true to ignore those warnings. This won't fix it however.

Please follow the issue template in the future.
Thanks
