### ISSUE TITLE
Problem with starting and joining

### ISSUE THREAD

**Issue by dobrac** [MylesIsCool/ViaVersion#516]
### What is the output link of /viaversion dump?
I am sorry, I didn't do it. When it happens again, I will add it. (I am using ViaVersion 0.9.9)

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I am using BungeeCord lastest version (#1191). I can list my plugins, but it won't tell you anything, because all plugins I did myself.

### How does this error happen? login? Using an item? 
This error happen on startup and prevents all players from joining.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Yes, there is an error: http://pastebin.com/aZek8Fyx
IPs ending with 241 or 205 are bungeecords and ip ending with 222 is server where this server is running.
Here is error from game: https://ctrlv.cz/shots/2016/10/16/Hvcx.png

**Comment by MylesIsCool** [comment]
ViaVersion dump is not time specific and just pulls information of your plugins.

Furthermore saying stuff like "I can list my plugins, but it won't tell you anything, because all plugins I did myself." just makes your report less useful.

I've never seen a case like this and would suspect it might be either:
Not loading the jar properly (downloaded wrong / something like that)
Reload issue if you used reload (but as your report said you didn't)


Going to close as this seems like a download issue, and if it was a problem the whole plugin wouldn't work after. If you get it more / can tell us how to reproduce, post the steps and we'll reopen it.

**Comment by dobrac** [comment]
I am sorry. I have more informations, but I just sticked to the questions... My fault....

So, if the dump is not time specific, here is it: http://hastebin.com/rosabapake.json

And something to the error: It happens just sometimes. Restart of the server is a solution, but the question is why is it happening? I thing, that if it is wrong downloaded version, it won't start at all.

Thank you for reading it.

**Comment by MylesIsCool** [comment]
@dobrac 

If it only happens at startup and sometimes works and sometimes doesn't. I suspect it might be your hard drive fails to read the jar file or something like that.

This is an extremely unusual issue.

**Comment by dobrac** [comment]
I have maybe one thing: It happens only on my lobby servers and these lobby servers are unique in one thing. They are being pinged by BungeeCords every x seconds and BungeeCord asks, if are they online.

This is done via this method: http://pastebin.com/uypTnWa2

**Comment by MylesIsCool** [comment]
@dobrac I'm not sure how that would break it, i've never seen any issues like this. And to me looks like a class loading issue, if you have time playing around with disabling things would be cool (on localhost maybe).
