### ISSUE TITLE
Viaversion and Customgui issue

### ISSUE THREAD

**Issue by xion87** [MylesIsCool/ViaVersion#522]
### What is the output link of /viaversion dump?
http://hastebin.com/enawudisog.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Waterfall 62 version

### How does this error happen? login? Using an item? 
When a player not using 1.8 version click the compass that must open the CustomGui server list and cause this error on console:
http://hastebin.com/iyewibukil.php
Is pretty spammy and allow the player to move items into his inventory.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://hastebin.com/iyewibukil.php

**Comment by MylesIsCool** [comment]
I can't help you with premium plugins unless it's replicated with a free one.

From what it seems, they use custom packets and they're not handling cancellation properly, I'd suggest contacting them as it's really their side (where the code happens) which can be fixed.

**Comment by xion87** [comment]
Author say that is a viaversion fault, and you say that is author fault... >.<

**Comment by MylesIsCool** [comment]
The issue presented is quite obviously reported multiple times throughout his plugin page.
"Caused by: net.minecraft.server.v1_8_R3.CancelledPacketHandleException"

ViaVersion is client sided (it only changes outgoing packets / incoming ones, with exception to a few listeners we use to make everything run smooth but none are inventory related).

You can't really expect us to debug a plugin we don't own / know the code for. I have a lot of friends using things like DeluxeMenus, ChestCommands and they all work fine. (Initially, we had some display issues with potions but they were sorted)

**Comment by xion87** [comment]
I think im gonna switch to DeluxeMenus, seem like pretty
