### ISSUE TITLE
1.9.4 - Server, 1.9 - 1.9.2 does not work with ProtocolSupport

### ISSUE THREAD

**Issue by LonelyTreeMc** [MylesIsCool/ViaVersion#615]
### What is the output link of /viaversion dump? 
Says failed to dump, please check console for more information
Console Message:
http://pastebin.com/VhxVtMx2

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord and Spigot 1.9.4
Plugins:
Spartans
ProtocolLib
ProtocolSupport (1.9.4 version)
ViaVersion most updated. 

### How does this error happen? login? Using an item? 
This happens when a player tries to join the server with 1.9 and 1.9.2

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/JWWT3qU5

**Comment by MylesIsCool** [comment]
Try latest dev build then do /viaver dump and provide output.

**Comment by LonelyTreeMc** [comment]
I have the latest version of ViaVersion which would be 1.0.3 
With what you said, I redownloaded and tried the command /viaver dump (same thing happened) 
Gave me this error message http://pastebin.com/TZRfHh8F

**Comment by MylesIsCool** [comment]
@LonelyTreeMc Latest dev build, http://ci.viaversion.com/job/ViaVersion/

**Comment by LonelyTreeMc** [comment]
https://gist.github.com/anonymous/018c6b930fd586cabd3f0d3638daa5f1 @MylesIsCool

**Comment by MylesIsCool** [comment]
I haven't fully looked into the issue but I remember somebody mentioning it a while ago, this is due to ProtocolSupport + ViaVersion trying to support 1.9.2 maybe?

I'm not sure if there's an easy workaround, I'll take a closer look sometime soon (exam season), it might be possible that changing the builds you're using of ProtocolSupport / Spigot fix the issue as it's a weird one.

**Comment by LonelyTreeMc** [comment]
Don't seem as putting via version in your bungeecord works also.
