### ISSUE TITLE
Currently an issue that I don't know how to fix?

### ISSUE THREAD

**Issue by KeystrokeProgramming** [MylesIsCool/ViaVersion#635]
### What is the output link of /viaversion dump? 
https://gist.github.com/b1cc770c21ff17384a59a6afd61a5ab3

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No, just Spigot for 1.8.8
http://prntscr.com/ed0r4l (Some are Custom, like Tester and HordeAddons)

### How does this error happen? login? Using an item? 
 I'm not quite sure, the console just constantly spams me with this error. I assume it happens when unsupported versions join the server, however I'm not entirely sure. It doesn't happen when I join, I'm running 1.8.4 and the server is 1.8.8

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/ubxq3zew There is no kick message, users don't get kicked just a big huge spam of constant errors in the console, it also seems to lag the server a little bit as well.

**Comment by MylesIsCool** [comment]
This is an issue with one of your plugins that uses custom mobs, "An error occurred with entity meta data for RABBIT OldID: 14"

This happens when a plugin sends incorrect data for the Minecraft version you're running (1.8.8), you can suppress these warnings in the ViaVersion config.yml, but be warned mobs may display differently. (suppress-metadata-errors in config.yml)
