### ISSUE TITLE
Error on login | TacoSpigot

### ISSUE THREAD

**Issue by SnakeDaoust1232** [MylesIsCool/ViaVersion#682]
### What is the output link of /viaversion dump? 
- https://gist.github.com/anonymous/596a59afe3f49191f9520908e0c9c646

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
- https://github.com/HexagonMC/BungeeCord
- https://ci.techcable.net/job/TacoSpigot-1.8.8/ (The issue is this. The newest commit)
  - https://github.com/TacoSpigot/TacoSpigot/commit/1ed1ff476881e2f8d6e93a72b0892cd18d26e87e

### How does this error happen? login? Using an item? 
- Login

### Is there an error in the console? Use pastebin.com. Is there a kick message?
- https://gyazo.com/c69a88b17888ea1bf5119433205639ce

When i try to join the hub
- https://gyazo.com/363ca9606bd7f8a8408980e603c3355f

**Comment by Matsv** [comment]
Could you try if this happens without ProtocolSupport?

**Comment by SnakeDaoust1232** [comment]
The issue is the tacospigot build. If i downgrade to 23 im able to join, as soon as i update to the latest build, it doesnt allow me to join.

**Comment by MylesIsCool** [comment]
I'd suggest downgrading as a solution, this isn't something we can fix really as it's down to internal changes in taco.

**Comment by SnakeDaoust1232** [comment]
Downgrading my tacospigot version? I waited months for the special request to be put into tacospigot.

**Comment by MylesIsCool** [comment]
The compatibility for 1.8 protocol support was designed for paper / spigot based on working with that software. The patch, https://github.com/TacoSpigot/TacoSpigot/commit/1ed1ff476881e2f8d6e93a72b0892cd18d26e87e#diff-cb2113b1d7c1823188e06fa4c5deadccR137 breaks because it's designed to work only with ProtocolSupport and not ViaVersion which ProtocolSupport 1.8.8 is tight getting compatibility as it is.
If you want support I would suggest asking Techcable nicely because it's not something that we can integrate without breaking our support for ProtocolSupport on other platforms.

**Comment by SnakeDaoust1232** [comment]
ok
