### ISSUE TITLE
mob subtypes show incorrectly on 1.11+ clients

### ISSUE THREAD

**Issue by SpEeD11** [MylesIsCool/ViaVersion#696]
Wither skeletons will often spawn visually as regular skeletons when using 1.11+ clients on a 1.8 server. This also happens with other mobs with subtypes such as zombies and zombie villagers. relogging fixes the issue

dump link: https://gist.github.com/anonymous/89eed521e04acfe6685b80c1f94500d0
using mythicmobs to spawn wither skeleton mobs easier, but I dont believe it changes the bug.

Reproduction steps:

1. log into server using 1.11 or 1.12 client
2. spawn a lot of wither skeletons (also happens with zombies spawning as zombie villagers but seems to be less common)
3. wither skeletons will often appear as regular skeletons
4. relogging displays the mobs as the correct subtype

no errors in console.

**Comment by MylesIsCool** [comment]
Unfortunately there's nothing ViaVersion can do without it having a huge overhead (we would need to save all information about all mobs per client, which would be potentially huge),

**Why does this happen?** Mojang changed the way some mob subtypes work, they are now their own mob so if a plugin changes the subtype after it's spawned we can't change the mob as there is no change mob packet (we'd have to completely respawn the mob and send all the data).


So the reason it doesn't happen when you relog is because all the mob data is sent when it spawns and ViaVersion can change the mob type when it spawns.
**So what can a plugin author do?** Ensure that when spawning a mob it's guaranteed to have the right subtype, using https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/World.html#spawn-org.bukkit.Location-java.lang.Class-org.bukkit.util.Consumer- in Bukkit is possibly the best way to guarantee this as it ensures the settings are attached when the mob is spawned.
