### ISSUE TITLE
1.12.x Client - Can't Push All Same Items on Shift + Double Click

### ISSUE THREAD

**Issue by bgencacat** [MylesIsCool/ViaVersion#739]
Client: 1.12.1
Server: 1.8.8 - Spigot

Ex: When players try to push all cobblestone blocks to chest same time using shift + double click on another cobblestone block in inventory, can't achieve this.

**Comment by v0idst4r** [comment]
Can confirm this happens to me

**Comment by Matsv** [comment]
Does this also happen in 1.8.x?

**Comment by v0idst4r** [comment]
I don't believe so.

**Comment by bgencacat** [comment]
There is no problem with 1.8.x client. Only 1.12.1 client with 1.8 server.

**Comment by v0idst4r** [comment]
@Matsv it wouldn't be a problem with viaversion if it happened on 1.8

**Comment by TrexSo** [comment]
I have same problem

**Comment by mmxw11** [comment]
I actually found the cause for this. 1.12+ clients sadly no longer send item data in QUICK MOVE action. 
This means we've to manually figure out what items each slot have based on the slot number the client sends. I'll try make a pull soon but sadly for now it will only affect bukkit/spigot.

**Comment by mmxw11** [comment]
Managed to get this work on 1.8 servers [video](https://www.youtube.com/watch?v=n566lwt8CC4&feature=youtu.be). 
Supporting it on 1.9+ servers shouldn't be hard because only one field was changed in the packet class data [structure](https://github.com/mmxw11/ViaVersion/blob/dev/bukkit/src/main/java/us/myles/ViaVersion/bukkit/providers/BukkitInvContainerItemProvider.java#L88).
@MylesIsCool Any feedback? https://github.com/mmxw11/ViaVersion/tree/dev
