### ISSUE TITLE
IndexOutOfBoundsException, Packet ID 0 ?

### ISSUE THREAD

**Issue by colinrgodsey** [MylesIsCool/ViaVersion#778]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/bae14ddd8c2e3981496d64c3b3653813

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Came from BungeeCord using viaversion. **_I am using viaversion and viabackwards on both bungee and my spigot servers._**

### How does this error happen? login? Using an item? 
No idea what triggers it, it just shows up from time to time in my log.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://gist.github.com/colinrgodsey/f5e17a343aa27984371fe6f3989100c7

**Comment by MylesIsCool** [comment]
Please fill out the issue fully or we're unable to assist you, the dump command can be run from the console.

**Comment by colinrgodsey** [comment]
didnt have permissions so cant dump without restarting bungee, assuming that also would destroy the dump. so, nothing to be done here

**Comment by colinrgodsey** [comment]
Issue is still coming up, including dump this time

**Comment by MylesIsCool** [comment]
I believe this error to be rather harmless, BaseProtocol is the ping stage of the Minecraft protocol. This means something is sending bad packet data to your server, you should be fine to ignore this. (You may want to lookup the IP that is doing this, perhaps a server list?)

We don't hide the error because sometimes we do slip up and need to see this kind of error, but in this case it seems to be something sending bad data.
