### ISSUE TITLE
Minecraft Pocket-/Windows 10-/Xbox Edition support

### ISSUE THREAD

**Issue by xXSchrandXx** [MylesIsCool/ViaVersion#794]
Feature request!

I know this could be very difficult, but can you implement an option for integrating the Minecraft Pocket / Windows 10 / Xbox Edition?

That would be great!

**Comment by krusic22** [comment]
Look at https://github.com/ProtocolSupport/ProtocolSupport
No point in reinventing the wheel.

**Comment by xXSchrandXx** [comment]
Seems that it won't work with Bungeecord

**Comment by electronicboy** [comment]
well, no; it won't work with bungeecord as that is entirely designed around the java editions protocol; the PE editions protocol doesn't even sit on the TCP network stack, so you'd need an entire different network pipeline to deal with traffic for PE. The amount of work involved is tremendous, I don't think it would even be remotely sane for a plugin such as ViaVersion to achieve this and would be better off sitting as a separate plugin instead of one that is designed to provide forwards protocol support to provide a completely different protocol ontop of it.

**Comment by krusic22** [comment]
It works with Bungee :P Look at ProtocolSupportBungee.

**Comment by xXSchrandXx** [comment]
ProtocolSupportBungee's support got abandoned. But the last dev Build works...

With those plugins I can Ping my Server, but I can't join them with another minecraft version than the "Orginal/Java Version"

**Comment by krusic22** [comment]
Last commit: a day ago
_>Abandoned_

**Comment by MrPowerGamerBR** [comment]
> ProtocolSupportBungee's support got abandoned. But the last dev Build works...

No, it isn't abandoned, Shevchik *did* drop the project earlier this year, but now he is updating it again and the latest dev build works fine.

ProtocolSupportBungee does work fine with any 1.4.7 - 1.6.4 clients on a 1.12.2 BungeeCord, PE support also works if the server uses ProtocolSupport (or if the server supports ProtocolSupport's encapsulation protocol, but that's an story for another day) but, of course, it is in pre-pre-pre-pre-pre-pre-pre-pre-alpha and it is VERY far from being stable for servers in production, but it is getting there.

**Comment by TheIntelloBox** [comment]
https://github.com/DragonetMC/DragonProxy/issues

It would be great if ViaVersion includes this.

**Comment by MylesIsCool** [comment]
See above if you want software that can do this, PS / DragonProxy are perfectly fine solutions (still in-dev of course). 

At this point in time, we have no plan to do this (see what electronicboy said).
