### ISSUE TITLE
Banner/Sign issues 1.8.8 server 1.9.4 client.

### ISSUE THREAD

**Issue by Roadhog360** [MylesIsCool/ViaVersion#840]
### What is the output link of /viaversion dump? 
![image](https://user-images.githubusercontent.com/11903511/41131465-8e714de6-6a81-11e8-9fb7-68743e78404e.png)
Fails to dump, puts this in console instead.

### How does this error happen? login? Using an item? 
Whole play session. 

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No error. No kick.

ISSUE:
First of all, I'm running VV1.3.0. Latest as of right now.
Banners signs, and possibly more don't render right when logging in. It's as if they have blank data. The only exception is when you log in while near one. For example, let's say I logged in facing a banner with a sign behind me. That banner shows, but the sign doesn't. Additionally, sometimes things just won't load up even if you are near them them when logging on. This is on 1.9.4 client with OptiFine installed, being the ONLY mod. The server is 1.8.8. Here's what the error looks like.
![image](https://user-images.githubusercontent.com/11903511/41131597-0eb38b90-6a82-11e8-8cae-fbd4488d2377.png)
I log in near banners. They render right.
However...
![image](https://user-images.githubusercontent.com/11903511/41131609-1bd06b2c-6a82-11e8-958f-6047059d2a9a.png)
These banners are blank. If you look closely, you can also see the signs were blank, too. As well as all of the signs that I wasn't facing when logging in.
Now, let's relog in the exact same position.
![image](https://user-images.githubusercontent.com/11903511/41131670-58d469b0-6a82-11e8-90ee-461fec0f2247.png)
(Sorry, accidentally walked a little, but you get the point.)
The BANK banners still won't display, but the signs inside are fine now.
Additionally, let's just press on to show how weird and random this issue is. I walk outside, nowhere near the bank or the police station, and...
![image](https://user-images.githubusercontent.com/11903511/41131769-d288384a-6a82-11e8-9690-a7bc81bd6682.png)
What's this!? The left banners are fine, but the ones on the right are black. The banners on the right should be green and white like the ones on the left, but they're all black.

Now, I know all of these signs and banners are fine, since logging on 1.8.8 makes everything work.

**Comment by Roadhog360** [comment]
UPDATE: Heads have this issue, too.
![image](https://user-images.githubusercontent.com/11903511/41131818-169464b4-6a83-11e8-904a-f1a0cb921423.png)

**Comment by Logics4** [comment]
The 1.3.0 version of ViaVersion from Spigot fails to dump because GitHub ended with the anonymous gists (which many plugins with functionalities of this style used). Myles and Mats have fixed this issue by basically making their own private service and updating the code to use it.
https://ci.viaversion.com/job/ViaVersion/193/
Using this build will allow you to run `/viaversion dump`correctly. Don't worry, it should be safe to use it in a production server since it comes from the master branch and not the DEV one.

**Comment by Logics4** [comment]
I think so, mostly little fixes that still didn't get into the SpigotMC Resources page.

**Comment by Roadhog360** [comment]
Alright, well it worked. Same issue though, but I got a dump now.
https://dump.viaversion.com/e59708eae50822452fb45b72cb57b08f76395c1e48caefc4c72a06770a91a5ef

**Comment by Roadhog360** [comment]
Tested, this bug happens on all versions, not just 1.9.4.
I still have the dump above for anyone willing to look at it.

**Comment by Roadhog360** [comment]
Bump.

**Comment by MylesIsCool** [comment]
This issue is down to chunk packets being not handled async by a plugin you have installed. Unless you can replicate this on a clean install of Spigot (request reopen), you'll have to identify the plugin. (Unfortunately, there's no magic way of doing this other than removing half and seeing if it happens to narrow it down, though the plugin will probably be NPC related / chunk loading related (eg. server signs)).

**Comment by Roadhog360** [comment]
After guessing with a few plugins, I have found it to be ProtocolSupportPotions.
I'll talk to its dev to see if ViaVersion badly reacts or it's a problem with his plugin.

**Comment by Roadhog360** [comment]
Turns out 1.8 servers don't even need that plugin since ViaRewind works with potions on its own there. Solved.
