### ISSUE TITLE
1.13 Connecting Blocks

### ISSUE THREAD

**Issue by MylesIsCool** [MylesIsCool/ViaVersion#856]
In Minecraft 1.13 the server now connects blocks by indicating a state for the block to use (north,east,south etc).

Blocks which have this issue:
- Redstone
- Doors
- Fences (Iron Bars too)
- Panes
- Stairs
- Chests
- Flowers

We're looking for suggestions/help implementing this as it's quite complicated to do at a protocol level.

We'll update this issue with progress (please don't bump etc). If you have any suggestions on a possible solution let us know.

Possible solutions off the top of my head:

- Cache chunks and calculate connections our self (heavily resource intensive)
- Use the main thread of the server and send the connection information to ViaVersion using NMS (somewhat complicated)
~~- Tell everyone to update to 1.13~~

All comments welcome :)

**Comment by TNTUP** [comment]
Affects Chests aswell. They don't connect^^

**Comment by Bobcat00** [comment]
I'd like to understand the issue.  In the old version, the server would send that there was, say, a fence at position A, a fence at position B, and the client would see they were adjacent and connect them.  In the new version, the server sends that there's a fence at A with a connection to the east, and a fence at B with a connection to the west?

If that's the case, ViaVersion has to emulate the functionality that was removed from the client.

The intuitively obvious way is to look at all 6(?) adjacent blocks and synthesize the connections.  Is that really resource intensive?  Isn't it just doing what the new 1.13 servers have to do anyway?  (And the old servers don't do.)  I suppose it might be problematic for blocks like chests, depending on how the old version stored the data.

I suppose different solutions could be implemented for different blocks.  Doors, for example, have fewer potential connections.  Maybe you could fix the doors before moving on to other blocks, although I admit that's probably more work in the end.

I noticed on my 1.8.8 server if I open a gate in a row of fences, all the adjacent fences on the same level become magically connected.  Not sure how that's happening.  Is it client side?

Sorry for not offering any real solutions.  I'm just trying to understand the situation and to spur some conversation.

**Comment by MylesIsCool** [comment]
It's done client side in below 1.13 (so yes 1.8), you can check adjacent blocks but this becomes an issue across chunks.

Clients may not have the same world as everyone else, so the obvious solution ends up looping through every block in a chunk storing every chunk and calculating connections (which to me, seems computationally expensive).

Just to try help you understand :)

**Comment by awgybop1** [comment]
This is a definite issue with NoCheatPlus on 1.8 servers as it sees the player as trying to walk inside of the block and therefore flags them as using "Phase". Could you somehow spoof this using client-side blocks so that the client understands they're connected? I know this would cause a little bit of server lag(not much) due to having to check their version and spoof this too them directly but it should still be doable nonetheless?

**Comment by awgybop1** [comment]
I've fixed the glass pane issue myself by simply placing a barrier block and then having an armor stand inside of it with the glass pane equipped on top of their head, and when breaking the block the armor stand disappears, the armor stand is rotated based on the direction the block was placed. This is definitely not an "optimal" solution but could be used as a temporary work-around.

**Comment by Bobcat00** [comment]
Thank you for your reply, Myles.  So I'm guessing that ViaVersion is only working with data in one chunk at a time, so it's unable to examine possible connecting blocks in adjacent chunks?  Well, that means you would only need to keep track of connections between chunks, i.e., on the chunk edges.  That's a 75% reduction in the number of blocks you need to examine.  Additionally, you only need to keep track of the connections that actually cross chunk boundaries, so most edge blocks will only have one possible connection.  That's all you'd need to cache.  All the other connections (intra-chunk) can be done when working with the chunk data.  And doors can't cross chunk boundaries at all, so that's even easier.  The same probably applies to flowers.  Does this make sense?

**Comment by ishland** [comment]
This bug is huge, players with 1.13 clients get stuck while walking on the fences.

**Comment by PureGero** [comment]
@Bobcat00 There's also fences, iron bars, glass panes etc. When a player places one of these, ViaVersion will need to calculate it's connections when the block update gets sent to other players. The adjacent blocks will also need to be recalculated if they're also fences, etc. You could cache all of these in the chunk, but they also connect to solid blocks, so you'd also need a boolean array of the entire chunk (whether the blocks are solid or not). This array will also have to stay up to date with any changes. 

Also, you'd need to cache this for every single player, which would become very resource hungry when you have 500+ players on a BungeeCord server. (None of this caching is required on the Spigot version as you could just ask the server for the block information)

Any better ideas?

**Comment by Bobcat00** [comment]
Ahhh, I forgot about BungeeCord.  Well, the bottom line is if you want to support 1.13, ViaVersion is going to have to provide the functionality that was removed from the client, one way or another.

**Comment by chilybones222** [comment]
I've noticed lava is also turned blue, and uses the same texture as water when a user is on 1.13 on a 1.12 generated world, along with the stair glitch as well.

**Comment by ishland** [comment]
You can place something next to them and change their status. And they will connect correctly. But you have to update them every chunk loading or join.

**Comment by Rukes** [comment]
Is this only client visual bug?

**Comment by awgybop1** [comment]
Yes, the blocks on the server are actually connected, your Minecraft 1.13 client just doesn't see it that way is all.

**Comment by roie123400010** [comment]
I just saw that you can fix that until you disconnect, just put fence gate near fence, open it, then break it and it should be fixed until you log off

**Comment by awgybop1** [comment]
TheHive uses ViaVersion...

**Comment by awgybop1** [comment]
![2018-07-24_22 15 54](https://user-images.githubusercontent.com/35583801/43177716-31eaa7d8-8f8f-11e8-878c-6259a9791d36.png)

**Comment by MylesIsCool** [comment]
@awgybop1 The hive also have custom software etc. They're able to do things we aren't easily able to. Developing the solution requires compatibility with several versions not just a few.

**Comment by MylesIsCool** [comment]
@ImEraze unfortunately these solutions will be heavily integrated into their software and won't really be what we can use :(

**Comment by HexedHero** [comment]
Been following this since the start, hope we can find out a fix. Hope all the best.

**Comment by 2001zhaozhao** [comment]
I would suggest that for now, just do it in any way that would fix the issue on some level, because it is so serious.

The problem basically deals with getting adjacent blocks around a target block at a protocol level. This encompasses basically everything bugged at the moment besides connected redstone wire at different y-levels, which I think is not too serious of an issue to leave alone for now.

In a chunk update packet, within the chunk you can feasibly check for the 4 adjacent blocks around the fence/wall/redstone in question. It's just blocks with a connection, blocks without a connection, and the edge case of stairs. (Even if you just do this, it would make a big difference.)

For blocks touching the edge of the chunk, check for any blocks in adjacent loaded chunks. 

On Bukkit you can just async-access the chunks, since AFAIK read calls do not cause any significant problems even if async. You could also use asyncworldedit API if available.

On bungee, you would have to cache the chunks for this to work - 2 bits per block face touching another chunk, on whether the block is solid and whether it would connect to redstone wire. (The block can also be fences, stone walls, or glass/glass panes themselves which have unique behavior, but we could use the fence-list to solve this, which I will explain below) This means 64x256x2 = 32,768 bits, or 4KB of memory per chunk. For a 16 render distance world, this is 4.3MB of memory per player, which is not so bad if you ask server owners to allocate extra RAM to bungee (besides, most servers have a much lower render distance). To determine when to unload a cached chunk from memory on bungeecord you would have to make a best guess of what the server render distance is, which shouldn't be too hard since you also have access to player move packets, etc.

If the block is touching an unloaded chunk, just leave it without a connection for now and cache the fence locations (with the connection info for the other faces) in question for when the adjacent chunk becomes loaded, in which case you can check if there is a connection and update the fence block in the previous chunk accordingly. This does produce an overhead at both client and server but would be the easiest way I can think of to overcome the problem.

**Comment by FurmigaHumana** [comment]
I dont think caching chunks on bungee side and calculating the conections there is a reliable fix for this issue, will work fine on small servers but on anything relatively bigger it would defenetly kill the performance, imagine caching chunks and calculating everything for over 2000 players!

Maybe the only solution for this right now would be fixing on spigot side but leave a know-bug note for bungee-only users.

**Comment by Matocolotoe** [comment]
You could just ask Hypixel developers ?

**Comment by bundabrg** [comment]
What about those who are using a server 1.13 or later. Is it worth detecting if this is the case and then just passing the state through without any modification? That way those with older server's will have this bug (and it can be gradually/hopefully solved) but those with newer servers can continue to work fine.

I've not studied this problem in depth enough to determine if this is possible so apologies if this is not possible.

**Comment by Logics4** [comment]
I don't think 1.13+ servers have this issue because they will handle the block connections as expected. The 1.13 client expects the 1.13 server to send that information to it, while in 1.12 block connections are handled at client-side.

**Comment by bundabrg** [comment]
My papermc server 1.13 connecting with a 1.13.1 client has this issue.

**Comment by bundabrg** [comment]
Sorry I think I'm going to take that back. Whilst I have this issue on one of my servers it still happens when I strip off every plugin and connect directly using a 1.13 client. I think its more to do with the fact I pasted a non 1.13 Schematic and the paste itself just inherits this issue (Which makes total sense). I tested this by copying a door exhibiting the behaviour to a schematic and then pasting it elsewhere with the effect copied as well. This may muddy the water somewhat when people report this issue.

**Comment by Herdsman45** [comment]
My case doesn't involve ViaVersion but maybe it will help, I have fences generated by PlotsSquared that are not connected with server and client both running 1.13, a block update to one fence makes them all connect. I didn't have ViaVersion installed at the time.

**Comment by SimonOrJ** [comment]
Using plugins for 1.12.2 and below or schematics with plugins not updated to 1.13 will have disconnected fences and panes, and that's the other plugin's issue and does not have anything to do with (packets send by) ViaVersion.

**Comment by Janmm14** [comment]
For bungeecord:
Don't cache whole chunks, just cache individual fence locations in a sent chunk. 

For spigot:
If chunk is loaded do check for fences near, otherwise don't.

**Comment by Matocolotoe** [comment]
This guy fixed the issue for most of the blocks that should be connected such as chests, fences...
https://github.com/Gerrygames/ViaVersion/
Class : https://github.com/Gerrygames/ViaVersion/tree/master/common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections

**Comment by AustinGarrettRichards** [comment]
> This guy fixed the issue for most of the blocks that should be connected such as chests, fences...
> https://github.com/Gerrygames/ViaVersion/
> Class : https://github.com/Gerrygames/ViaVersion/tree/master/common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections
> And it works pretty well (I tested it)

I tried this and it did not work at all. Even merged changes with the newest via version. Was using a 1.13 client on a 1.12.2 server.

**Comment by Chevels** [comment]
> 
> 
> @Gerrygames fixed the issue for most of the blocks that should be connected such as chests, fences...
> https://github.com/Gerrygames/ViaVersion/
> Class : https://github.com/Gerrygames/ViaVersion/tree/master/common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections
> And it works pretty well (I tested it) + 0 lag

Hello,
I would like to try because this problem is very embarrassing, and since time it becomes urgent to fix it especially for doors, but I can not find the .jar? Do you know where I can find it?

**Comment by toxamin** [comment]
you uh.. compile it?

**Comment by Chevels** [comment]
Ok that's what I feared. I do not know how to do it, I'll wait until Viaversion is officially updated. Thank you for your answer :)

**Comment by Chevels** [comment]
The problem is that I don't even know where to start^^ I don't know what to compile, what files to download etc. I am a girl full of good will but I would need at least a base for me to learn.

Thank you for your answer, I'll try to learn about "how to do" when I have some free time. Good night!

**Comment by awgybop1** [comment]
Compiling is easy. You need to clone the githib repo, open it in Java
Eclipse and then export it as a jar file.

**Comment by creeper123123321** [comment]
1 - Install JDK
2 - Install Maven
3 - Clone the GitHub repo or download as a zip
4 - Run the command ``mvn package`` in the folder that has a pom.xml
5 - Get the jar from jar/target/ViaVersion-[version].jar

**Comment by Chevels** [comment]
Thanks a lot for your help!

Unfortunately, I had false hopes. JDK refuses to install on my PC (yet I download the right version corresponding to my Windows 7 64bits) and when I start the installation, I do "run as administrator", I click on "accept the execution of this file" then nothing happens. No error message, but no JDK either on my hard drive. It's been over an hour and a half since I tried various solutions found on the internet (apparently this problem happens to other people) but nothing works.
It's a shame but I am forced to wait for an official update of ViaVersion... So close to the goal it's a bit annoying.

Good bye guys and sorry for the off topic :)

**Comment by ishland** [comment]
@Chevels I think you can build on a linux machine.

**Comment by Chevels** [comment]
Thank you for your answer @ishland but I will not mount a PC under Linux just to compile a Java plugin once in my life. I think I have enough galley like that, maybe I will eventually find a charitable soul who wants to give me a jar already compiled.
Otherwise I will wait for an official update...

Bye!

**Comment by awgybop1** [comment]
Since you don't understand what to do, I'll be nice and do it for you.

**Comment by awgybop1** [comment]
[https://drive.google.com/open?id=1Hc2HZKeiEP_iud1xqlZXy8Yr-VLTX-wg](url)

**Comment by Chevels** [comment]
Thank you very much @awgybop1 !! You are super nice! :)
Once again, sorry for asking you. At least I know how to do now and when I'll have more time, I will try to understand why this damn JDK refuses to install. I don't like to stay on a defeat in front of a PC^^

Kiss to all!

**Comment by AustinGarrettRichards** [comment]
Any status on the additional blocks/connections? A lot are still missing/not working fully like stairs, etc.

**Comment by Matocolotoe** [comment]
If you are talking about the fork of Gerrygames ask him for the connected blocks
But for the official ViaVersion I don't know, it could be very fast or very slow to fix this

**Comment by awgybop1** [comment]
I've been experimenting with stairs and I've got them to almost work perfect, but not always, and sometimes they completely go invisible upon client re-login..

**Comment by RepublicanSensei** [comment]
Maybe detect these blocks on block place event and set block as placed blocks?

**Comment by Janmm14** [comment]
> Maybe detect these blocks on block place event and set block as placed blocks?

Don't see how that could fix this issue.

**Comment by smmmadden** [comment]
1.6.0 made no difference in fences or doors for 1.12.2.

**Comment by rukenantoni** [comment]
how are hypixel doing it

**Comment by DutchUser** [comment]
Custom plugin. They dont use ViaVersion.

**Comment by sgdc3** [comment]
I added @Gerrygames 's fork to my jenkins instance at: https://ci.codemc.org/job/ThirdParty/job/ViaVersion-ConnectingBlocks/

**Comment by rukenantoni** [comment]
> I added @Gerrygames 's fork to my jenkins instance at: https://ci.codemc.org/job/ThirdParty/job/ViaVersion-ConnectingBlocks/

only stairs not working

**Comment by AustinGarrettRichards** [comment]
> I added @Gerrygames 's fork to my jenkins instance at: https://ci.codemc.org/job/ThirdParty/job/ViaVersion-ConnectingBlocks/

This is wonderful. Everything works except double tall plants. :)
This is a pretty great solution though and we're very close now :D

**Comment by PinkLolicorn** [comment]
I think @Gerrygames's version is real memory eater.

![suspect](https://user-images.githubusercontent.com/44551064/47618562-1a5d2000-dad5-11e8-99ec-dc6fa536c8c6.png)
![suspect_details](https://user-images.githubusercontent.com/44551064/47618566-221cc480-dad5-11e8-867f-2a45dc335d8a.png)

I do not recommend using this version for servers with more than 20 players online, especially for creative servers.

**Comment by MylesIsCool** [comment]
See https://github.com/MylesIsCool/ViaVersion/pull/1061 for progress.

**Comment by mcraftpete** [comment]
I agree with someone else , using the GerryGames version has bad memory leak , i used it on bungee and after a few hours server crashes with out of memory , removing it the leak is gone.

**Comment by ForceUpdate1** [comment]
@mcraftpete 
It is not recommended to use this version on the bungee cord.
Besides, this version is not up to date.

**Comment by MylesIsCool** [comment]
Block connections will be available in the next release / also on our CI.

**Comment by bundabrg** [comment]
I assume this does not yet work for ViaVersion on Bungeecord? I downloaded the latest release from CI and installed to my Bungee server but still get glitchy doors on the backend. 

In my case I can't install it on the backend server because the backend is a 1.12-R2 vanilla server.

**Comment by Gerrygames** [comment]
You have to enable the config option @bundabrg

**Comment by Germanode** [comment]
Happening with tall grass too. 1.12.2 Tall grass appears as grass and a flower on top on 1.13.2.

**Comment by williamd5** [comment]
Issue persists on 4.0.0:
- glass panes are not connected
- cobblestone walls not shown at all (client is able to walk though them until block update is caused nearby)
- wood fences do not connect and one is able to walk between them
- doors sometimes have wrong orientation and are _half_ open
- trapdoors have incorrect open/close state that updates on nearby block update
Running on Paper 1.16.5 with ProtocolLib and Viabackwards

**Comment by Jo0001** [comment]
This issues was fixed a long time ago and no one reported it recently.
Try it on a new server with just Via* installed and if it still happens, open a *new* issue

**Comment by williamd5** [comment]
How much newer than Paper 1.16.5 can I do?

**Comment by Jo0001** [comment]
With new a mean a fresh (test) server with just Via installed.
If the issue then  still persits, please **open a new issue!**
