### ISSUE TITLE
ViaVersion on 1.12.2 Bungee + PS on spigot 1.12.2 NP on InventoryPackets.toClient

### ISSUE THREAD

**Issue by i9hdkill** [MylesIsCool/ViaVersion#868]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/560657f96d90de217a87f73178ca6c41c2838670eb803832acf9abcda7b28a3a

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
HexaCord

### How does this error happen? login? Using an item? 
Happens on login (Items are given at login)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/Rh1RT802
I am on a 1.12.2 server with PS installed. using /lobby to try to connect to our 1.12.2 + PS lobby server

**Comment by Matsv** [comment]
Thanks for reporting!

Should be fixed since commit [4c8761b17b991072b2d156bc876caefcfa12c847](https://github.com/MylesIsCool/ViaVersion/commit/4c8761b17b991072b2d156bc876caefcfa12c847#diff-6d3a856211e2df1e3a39fcdd2c831c09L334)!
Please try the latest devbuild (https://ci.viaversion.com/job/ViaVersion/).

Ask for a reopen if the issue still occurs (:

**Comment by i9hdkill** [comment]
Fixed it thanks. But getting spammed with
[INFORMATION] FAILED TO GET 1.13 ITEM FOR 383
when a 1.13 connected to that spigot server
