### ISSUE TITLE
server-icon.png does not show up in 1.13 client when selecting servers

### ISSUE THREAD

**Issue by kalendae** [MylesIsCool/ViaVersion#886]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/573219c69a5ea7638b42e73fe2add5828826e855bc8ef5450a6cb2200ffd752f

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
no bungeecord but using essentialsX and multiversecore

### How does this error happen? login? Using an item? 
when viewing servers in the Play Multiplayer screen in 1.13, instead of showing the server-icon.png image (which 1.12.2 clients see) the default server icon image is used.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
no, user has not connected yet

**Comment by yzimroni** [comment]
It's a minecraft bug, seems like the favicon in 1.12.2 are encoded to base64 with \n (new line character), and in 1.13 they are encoded properly, without \n.
It can be fixed in ViaVersion (https://github.com/yzimroni/ViaVersion/commit/20128a2309a8396da8d17553b5391ac962ce2726), the question is whether we want to fix it in ViaVersion or let mojang fix it, since its a minecraft bug.
