### ISSUE TITLE
1.8.8 - io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.

### ISSUE THREAD

**Issue by minecraft7net** [MylesIsCool/ViaVersion#934]
### What is the output link of /viaversion dump? 

https://dump.viaversion.com/7d06e75e33a9888aa8057b183dc39c5cd1925a69957dc1d448ef59997e63706f

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

yes - travertine b58

### How does this error happen? login? Using an item? 

when player join (?) over travertine to hub - hard to say when exacly but i have many errors like this on but. i turned on debug and log is more detailed.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

[17:08:55] [Server thread/INFO]: This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

[17:08:57] [Server thread/INFO]: [ViaVersion] Loading ViaVersion v1.4.2-SNAPSHOT

https://pastebin.com/1tpw2D1A

**Comment by MylesIsCool** [comment]
Could you try with updated BungeeCord? If persists, provide the new error :)

**Comment by electronicboy** [comment]
```
[13:03:34] [Netty Epoll Server IO #0/WARN]: Caused by: io.netty.handler.codec.DecoderException: The received string length is longer than maximum allowed (22 > 20)
[13:03:34] [Netty Epoll Server IO #0/WARN]:     at net.minecraft.server.v1_8_R3.PacketDataSerializer.c(PacketDataSerializer.java:227)
[13:03:34] [Netty Epoll Server IO #0/WARN]:     at net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload.a(SourceFile:39)
```

You have a plugin that is sending plugin messages that are too long, likely due to bungeecord rewriting plugin messages on 1.13 connections however 1.12.2 and lower only accept plugin messages up to a certain size

**Comment by minecraft7net** [comment]
i'm trying to find this 2 weeks.

one was FastLogin update (thanks)

but now i don't know because i cannot replay this - its random from part of players

**Comment by minecraft7net** [comment]
Travertine - b 59 error log

https://pastebin.com/9bHvs5ZL

paperclip 1.8.8

https://pastebin.com/is5T33dF
https://pastebin.com/RyegxkTL

**Comment by minecraft7net** [comment]
bungeecord b1344

09:17:48 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.13-SNAPSHOT:715ec07:1344

spigot 1.8.8
https://pastebin.com/8JeMJz4p

**Comment by electronicboy** [comment]
Ultimately, I have no idea what fix you're expecting from ViaVersion here,the only real "fixes" I can see here are each as horrible as the next:
1) Handle this packet inside of the plugin and don't let the server itself process it
2) Truncate these messages, would require VV to cut them, and leave these messages broken
3) cancel them - They're likely not going to work anyways
4) have a user configurable translation table, so that owners can provide a list of 1.13 > legacy channel names - Gross, requires server owners to be able to research/pull the information required, or relies on VV to provide mappings for everything somebody might be using...

Options 1 -> 3 are going to leave these messages broken, but will stop kicks due to this... Option 4 will just be a maintenance burden on somebody...
