### ISSUE TITLE
ViaVersion possibly breaking protocol version constant when adding 1.13 support behind BungeeCord.

### ISSUE THREAD

**Issue by mibby** [MylesIsCool/ViaVersion#982]
RE: https://github.com/Phoenix616/ResourcepacksPlugins/issues/13#issuecomment-414159502

Running into an issue with a plugin not returning the correct resource pack format version for clients 1.13 (and above). Reporting the issue to the plugin (BungeeResourcePack), they claim perhaps your method of adding support is messing up Bungee PendingConnection#getVersion logic?

**Proxy Environment**
Waterfall build 218 (Bungee 1.8-1.13)
ViaVersion-DEV build 154 (to allow 1.13 clients to connect to 1.12.2 server)
BungeeResourcePack build 215

**Server Environment**
Paper dev 1547 (Spigot 1.12.2)
ProtocolSupport build 242 (to allow <1.12 clients to connect to the server) -- (last Spigot 1.12.2 supported build - custom compiled without | symbol to allow 1.13 clients to connect without crashing.)

ViaVersion Dump
https://dump.viaversion.com/959b652dda6ad1b730ac2db84ff84c7dcc75d0511c870f0ca8674b576e8d1c8d

**Comment by mibby** [comment]
That's where I'm confused too. My Bungee (Waterfall) version _should_ support 1.13 natively with ViaVersion just doing all the work to remap 1.13 to a 1.12 server for connecting. But for some reason BungeeResourcePack isn't detecting 1.13 players connecting through Bungee as being on 1.13, even though Via reports the client as 1.13 with ```/viaversion pps```. Unless there is a problem within BungeeResourcePack's version detection?

@Phoenix616 says he had a similar report with Bungee and ViaVersion, so it's possible there is a discrepancy somewhere.

**Comment by MylesIsCool** [comment]
Unfortunately, there's no simple solution to this other than asking others to use our API.

Why? Because Bungee needs the handshake value setting for emulating that version on join

https://github.com/MylesIsCool/ViaVersion/blob/master/bungee/src/main/java/us/myles/ViaVersion/bungee/handlers/BungeeServerHandler.java#L71

Which is the same used for getVersion() hence why it causes issues, the ideal solution is always using VV on Bukkit of course :P
